name: Trigger add to board
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  set-item-data:
    if: github.event.label.name == 'Core Contributor assignee'
    runs-on: ubuntu-latest
    outputs:
      item_type: ${{ steps.set-type.outputs.item_type }}
      item_number: ${{ steps.set-type.outputs.item_number }}
    steps:
      - name: Set item type and number
        id: set-type
        run: |
          if [[ "${{ github.event.issue.number }}" != "" ]]; then
            echo "item_type=issue" >> $GITHUB_OUTPUT
            echo "item_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
          else
            echo "item_type=pull_request" >> $GITHUB_OUTPUT
            echo "item_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          fi

  add-to-cc-board:
    needs: set-item-data
    if: github.event.label.name == 'Core Contributor assignee'
    uses: ChrisChV-Sandbox-Organization/.github/.github/workflows/add-to-cc-board.yml@main
    with:
      item_number: ${{ needs.prepare.outputs.item_number }}
      board_name: cc-edx-platform
      repo_name: ${{ github.repository }}
      item_type: ${{ needs.prepare.outputs.item_type }}
